name: database
on:
  - push
  - pull_request
jobs:
  generate-prisma:
    name: generate prisma schema
    runs-on: ubuntu-latest
    container: node:16
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:5432/groovox
      POSTGRES_USER: groovox
      POSTGRES_PASSWORD: groovox
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: migrate
        uses: joshuaavalon/flyway-action@v1
        with:
          url: jdbc:postgresql://postgres:5432/postgres
          user: ${{ env.POSTGRES_USER }}
          password: ${{ env.POSTGRES_PASSWORD }}
          location: filesystem:./database/migrations
      - name: install dependencies
        run: npm ci
      - name: reset schema
        run: cp packages/database/schema.template.prisma packages/database/schema.prisma
      - name: introspect database
        run: npm run introspect
      - name: generate schema
        run: npm run generate:database
      - uses: actions/upload-artifact@v2
        with:
          name: schema.prisma
          path: packages/database/schema.prisma
